// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckForUpdate():Promise<main.UpdateStatus>;

export function GetCurrentVersion():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function PerformUpdate():Promise<boolean>;
